### PR TITLE
Treat new PUT request properties as compatible again

### LINKED ISSUE #537: Treat new PUT request properties as compatible
Currently new PUT request properties are treated as incompatible. This is due to #136 (with PR #137) which appear invalid in intent, implementation, and test.
- Invalid in intent: #136 claims that adding a readOnly property to the request body of a PUT request is a breaking change because clients will begin to omit it and the server will interpret the omission as a directive to delete the property. This is incorrect because the server should expect, [per the OAS spec](https://spec.openapis.org/oas/v3.0.3#fixed-fields-19), that readOnly properties "SHOULD NOT be sent as part of the request". So it would be a bug for the server to delete any data associated with the readOnly property. Regardless, the API is left unbroken if the server simply ignores readOnly properties.
- Invalid in implementation: the code treats as incompatible any new PUT request property, not just readOnly properties.
- Invalid in test: no readOnly properties are tested.

In theory one could argue that some servers might enforce the "SHOULD NOT" language of the spec by returning validation errors where they didn't before, and this would constitute an API breakage. But that should be discussed in a different issue.

### PR DESCRIPTION
**Pull request by westse**
Effectively reverts change for #136 (and PR #137) which appear invalid in intent, implementation, and test.
- Invalid in intent: #136 claims that adding a readOnly property to the request body of a PUT request is a breaking change because clients will begin to omit it and the server will interpret the omission as a directive to delete the property. This is incorrect because the server should expect, [per the OAS spec](https://spec.openapis.org/oas/v3.0.3#fixed-fields-19), that readOnly properties "SHOULD NOT be sent as part of the request". So it would be a bug for the server to delete any data associated with the readOnly property. Regardless, the API is left unbroken if the server simply ignores readOnly properties.
- Invalid in implementation: the code treats as incompatible any new PUT request property, not just readOnly properties.
- Invalid in test: no readOnly properties are tested.

In theory one could argue that some servers might enforce the "SHOULD NOT" language of the spec by returning validation errors where they didn't before, and this would constitute an API breakage. But that should be discussed in a different issue.

Fixes #537
Refs #136
Refs #137

### CODE REVIEW

File: core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java [hunk 1]
```diff
@@ -1,21 +0,0 @@
...
-  private final String OPENAPI_DOC1 = "add-prop-put-1.yaml";
-  private final String OPENAPI_DOC2 = "add-prop-put-2.yaml";
-
-  @Test
-  public void testDiffSame() {
-    assertOpenApiAreEquals(OPENAPI_DOC1, OPENAPI_DOC1);
-  }
-
-  @Test
-  public void testDiffDifferent() {
```
Comment (mas-chen) [inline core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java:18]: I don't think we should remove this test. In fact they should be kept to check that the two docs are indeed compatible.

So we should have a `testFieldAdditionalInPutApiIsCompatible` or something similar

Comment (westse) [reply core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java:18]: @mas-chen Good point about not losing a test. I think my #546 PR will address this.

Comment (westse) [reply core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java:18]: Fair enough. I've made your suggested changes. Look ok?

**Review by mas-chen — APPROVED** [review]

File: core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java (hunk 1 above)
Comment (mas-chen) [reply core/src/test/java/org/openapitools/openapidiff/core/AddPropPutDiffTest.java:18]: Looks good to me but I'm not a contributor, would be good to get the help of one to merge this fix
